export const SCHOOL_OPTIONS = [
  "Biotehniški center Naklo",
  "Biotehniški center Naklo, Srednja šola",
  "Ekonomska gimnazija in srednja šola Radovljica",
  "Gimnazija Franceta Prešerna",
  "Gimnazija Jesenice",
  "Gimnazija Kranj",
  "Gimnazija Škofja Loka",
  "Srednja šola Jesenice",
  "Srednješolski izobraževalni center Radovljica",
  "Šolski center Kranj",
  "Šolski center Kranj, Srednja ekonomska, storitvena in gradbena šola",
  "Šolski center Kranj, Srednja tehniška šola",
  "Šolski center Kranj, Strokovna gimnazija",
  "Šolski center Škofja Loka",
  "Šolski center Škofja Loka, Srednja šola za lesarstvo",
  "Šolski center Škofja Loka, Srednja šola za strojništvo",
  "Gimnazija Jurija Vege Idrija",
  "Gimnazija Nova Gorica",
  "Gimnazija Tolmin",
  "Srednja šola Veno Pilon Ajdovščina",
  "Škofijska gimnazija Vipava",
  "Šolski center Nova Gorica",
  "Šolski center Nova Gorica, Biotehniška šola",
  "Šolski center Nova Gorica, Elektrotehniška in računalniška šola",
  "Šolski center Nova Gorica, Gimnazija in zdravstvena šola",
  "Šolski center Nova Gorica, Srednja ekonomska in trgovska šola",
  "Šolski center Nova Gorica, Strojna, prometna in lesarska šola",
  "Ekonomska šola Novo mesto, Srednja šola in gimnazija",
  "Gimnazija in srednja šola Kočevje",
  "Gimnazija Novo mesto",
  "Grm Novo mesto - center biotehnike in turizma",
  "Grm Novo mesto - center biotehnike in turizma, Kmetijska šola Grm in biotehniška gimnazija",
  "Grm Novo mesto - center biotehnike in turizma, Srednja šola za gostinstvo in turizem z dijaškim in študentskim domom",
  "Srednja šola Črnomelj",
  "Šolski center Novo mesto, Srednja elektro-računalniška šola in tehniška gimnazija",
  "Šolski center Novo mesto, Srednja gradbena, lesarska in vzgojiteljska šola",
  "Šolski center Novo mesto, Srednja strojna šola",
  "Šolski center Novo mesto, Srednja zdravstvena in kemijska šola",
  "Šolski center Ravne na Koroškem",
  "Šolski center Ravne na Koroškem, Gimnazija",
  "Šolski center Ravne na Koroškem, Srednja šola",
  "Šolski center Slovenj Gradec",
  "Šolski center Slovenj Gradec, Gimnazija",
  "Šolski center Slovenj Gradec, Srednja šola Slovenj Gradec in Muta",
  "Šolski center Slovenj Gradec, Srednja zdravstvena šola",
  "Gimnazija Antonio Sema Piran",
  "Gimnazija, elektro in pomorska šola Piran",
  "Gimnazija Gian Rinaldo Carli Koper",
  "Gimnazija Koper",
  "Srednja ekonomsko - poslovna šola Koper",
  "Srednja šola Izola",
  "Srednja šola Pietro Coppo Izola",
  "Srednja tehniška šola Koper",
  "Šolski center Srečka Kosovela Sežana, Gimnazija in ekonomska šola",
  "Biotehniški izobraževalni center Ljubljana",
  "Biotehniški izobraževalni center Ljubljana, Gimnazija in veterinarska šola",
  "Biotehniški izobraževalni center Ljubljana, Živilska in naravovarstvena šola",
  "Center za izobraževanje, rehabilitacijo in usposabljanje Kamnik, Srednja šola",
  "Ekonomska šola Ljubljana",
  "Elektrotehniško-računalniška strokovna šola in gimnazija Ljubljana",
  "ERUDIO Srednja šola",
  "ERUDIO ZASEBNA GIMNAZIJA, Zavod za izobraževanje",
  "Gimnazija Bežigrad",
  "Gimnazija Bežigrad, Gimnazija",
  "Gimnazija Bežigrad, Mednarodna šola",
  "Gimnazija in srednja šola Rudolfa Maistra Kamnik",
  "Gimnazija Jožeta Plečnika Ljubljana",
  "Gimnazija Ledina",
  "Gimnazija Moste",
  "Gimnazija Poljane",
  "Gimnazija Šentvid",
  "Gimnazija Šiška",
  "Gimnazija Vič",
  "Konservatorij za glasbo in balet Ljubljana, Srednja glasbena in baletna šola",
  "Srednja ekonomska šola Ljubljana",
  "Srednja frizerska šola Ljubljana",
  "Srednja gradbena, geodetska, okoljevarstvena šola in strokovna gimnazija Ljubljana",
  "Srednja medijska in grafična šola Ljubljana",
  "Srednja šola Domžale",
  "Srednja šola Domžale, Gimnazija",
  "Srednja šola Domžale, Poklicna in strokovna šola",
  "Srednja šola Josipa Jurčiča Ivančna Gorica",
  "Srednja šola tehniških strok Šiška",
  "Srednja šola za farmacijo, kozmetiko in zdravstvo",
  "Srednja šola za gastronomijo in turizem Ljubljana",
  "Srednja šola za oblikovanje in fotografijo Ljubljana",
  "Srednja trgovska in aranžerska šola Ljubljana",
  "Srednja upravno administrativna šola Ljubljana",
  "Srednja vzgojiteljska šola, gimnazija in umetniška gimnazija Ljubljana",
  "Srednja zdravstvena šola Ljubljana",
  "Strokovni izobraževalni center Ljubljana",
  "Strokovni izobraževalni center Ljubljana, Srednja poklicna in strokovna šola Bežigrad",
  "Strokovni izobraževalni center Ljubljana, Srednja šola za logistiko in tekstilstvo",
  "Strokovni izobraževalni center Ljubljana, Srednja šola za strojništvo in mehatroniko",
  "Šolski center Ljubljana",
  "Šolski center Ljubljana, Gimnazija Antona Aškerca",
  "Šolski center Ljubljana, Srednja lesarska šola",
  "Šolski center Ljubljana, Srednja šola za strojništvo, kemijo in varovanje",
  "Šolski center za pošto, ekonomijo in telekomunikacije Ljubljana",
  "Šolski center za pošto, ekonomijo in telekomunikacije Ljubljana, Srednja tehniška in strokovna šola",
  "Zavod sv. Frančiška Saleškega",
  "Zavod sv. Frančiška Saleškega, Gimnazija Želimlje",
  "Zavod sv. Stanislava",
  "Zavod sv. Stanislava, Škofijska klasična gimnazija",
  "Zavod za gluhe in naglušne Ljubljana, Srednja šola in dom",
  "Biotehniška šola Maribor",
  "Gimnazija in srednja šola za kemijo in farmacijo Ruše",
  "Gimnazija Ormož",
  "Gimnazija Ptuj",
  "II. gimnazija Maribor",
  "III. gimnazija Maribor",
  "Izobraževalni center Piramida Maribor",
  "Izobraževalni center Piramida Maribor, Srednja šola za prehrano in živilstvo",
  "Konservatorij za glasbo in balet Maribor",
  "Lesarska šola Maribor",
  "Lesarska šola Maribor, Srednja lesarska in gozdarska šola",
  "Prometna šola Maribor",
  "Prometna šola Maribor, Srednja prometna šola in dijaški dom",
  "Prva gimnazija Maribor",
  "Srednja ekonomska šola in gimnazija Maribor",
  "Srednja elektro-računalniška šola Maribor",
  "Srednja gradbena šola in gimnazija Maribor",
  "Srednja šola Slovenska Bistrica",
  "Srednja šola za gostinstvo in turizem Maribor",
  "Srednja šola za oblikovanje Maribor",
  "Srednja šola za trženje in dizajn Maribor",
  "Srednja zdravstvena in kozmetična šola Maribor",
  "Šolski center Ptuj",
  "Šolski center Ptuj, Elektro in računalniška šola",
  "Šolski center Ptuj, Strojna šola",
  "Šolski center Ptuj, Šola za ekonomijo, turizem in kmetijstvo",
  "Tehniški šolski center Maribor",
  "Tehniški šolski center Maribor, Srednja strojna šola",
  "Zavod Antona Martina Slomška",
  "Zavod Antona Martina Slomška, Škofijska gimnazija Antona Martina Slomška",
  "Biotehniška šola Rakičan",
  "Dvojezična srednja šola Lendava",
  "Ekonomska šola Murska Sobota",
  "Ekonomska šola Murska Sobota, Srednja šola in gimnazija",
  "Gimnazija Franca Miklošiča Ljutomer",
  "Gimnazija Murska Sobota",
  "Srednja poklicna in tehniška šola Murska Sobota",
  "Srednja šola za gostinstvo in turizem Radenci",
  "Srednja zdravstvena šola Murska Sobota",
  "Gimnazija Brežice",
  "Strokovno izobraževalni center Brežice",
  "Strokovno izobraževalni center Brežice, Srednja šola",
  "Šolski center Krško - Sevnica",
  "Šolski center Krško - Sevnica, Srednja šola Krško",
  "Šolski center Krško - Sevnica, Srednja šola Sevnica",
  "Srednja gozdarska, lesarska in zdravstvena šola Postojna",
  "Šolski center Postojna",
  "Šolski center Postojna, Gimnazija, vzgojiteljska in računalniška šola",
  "Šolski center Postojna, Gimnazija, vzgojiteljska in računalniška šola Ilirska Bistrica",
  "Šolski center Postojna, Srednja strojna in ekonomska šola",
  "Ekonomska šola Celje",
  "Ekonomska šola Celje, Gimnazija in srednja šola",
  "Gimnazija Celje - Center",
  "I. gimnazija v Celju",
  "Srednja zdravstvena in kozmetična šola Celje",
  "Strokovni izobraževalni center Alme M. Karlin",
  "Šola za hortikulturo in vizualne umetnosti Celje",
  "Šola za hortikulturo in vizualne umetnosti Celje, Srednja poklicna in strokovna šola",
  "Šolski center Celje",
  "Šolski center Celje, Gimnazija Lava",
  "Šolski center Celje, Srednja šola za gradbeništvo in varovanje okolja",
  "Šolski center Celje, Srednja šola za kemijo, elektrotehniko in računalništvo",
  "Šolski center Celje, Srednja šola za storitvene dejavnosti in logistiko",
  "Šolski center Celje, Srednja šola za strojništvo, mehatroniko in medije",
  "Šolski center Rogaška Slatina",
  "Šolski center Slovenske Konjice - Zreče",
  "Šolski center Slovenske Konjice - Zreče, Gimnazija Slovenske Konjice",
  "Šolski center Slovenske Konjice - Zreče, Srednja poklicna in strokovna šola Zreče",
  "Šolski center Šentjur",
  "Šolski center Šentjur, Srednja poklicna in strokovna šola",
  "Šolski center Velenje",
  "Šolski center Velenje, Elektro in računalniška šola",
  "Šolski center Velenje, Gimnazija",
  "Šolski center Velenje, Šola za storitvene dejavnosti",
  "Šolski center Velenje, Šola za strojništvo, geotehniko in okolje",
  "Gimnazija in ekonomska srednja šola Trbovlje",
  "Gimnazija Litija",
  "Srednja šola Zagorje",
  "Srednja tehniška in poklicna šola Trbovlje",
] as const;

export function isSchoolOption(value: string) {
  return SCHOOL_OPTIONS.includes(value as (typeof SCHOOL_OPTIONS)[number]);
}
